// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SredstvaData;

#nullable disable

namespace SredstvaData.Migrations
{
    [DbContext(typeof(SredstvaDbContext))]
    [Migration("20260729100300_DodajPoreskaPoljaSredstva")]
    partial class DodajPoreskaPoljaSredstva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("SredstvaData.Models.ClanKomisije", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KomisijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KomisijaId");

                    b.ToTable("ClanoviKomisije");
                });

            modelBuilder.Entity("SredstvaData.Models.Dobavljac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Konto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MestoIBroj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpisKonta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UlicaIBroj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dobavljaci");
                });

            modelBuilder.Entity("SredstvaData.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaticniBroj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PIB")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firme");
                });

            modelBuilder.Entity("SredstvaData.Models.Kartica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmortizacionaGrupa1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmortizacionaGrupa2")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IspravkaVrednosti")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KoeficijentRevalorizacije")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObracunskaJedinica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpisPromene")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RedBroj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SredstvoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopaAmortizacije")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SredstvoId");

                    b.ToTable("Kartice");
                });

            modelBuilder.Entity("SredstvaData.Models.Komisija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<bool>("JeAktivna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Komisije");
                });

            modelBuilder.Entity("SredstvaData.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("JeAktivan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Uloga")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImePrezime = "Administrator",
                            JeAktivan = true,
                            KorisnickoIme = "admin",
                            LozinkaHash = "PBKDF2$100000$9HpsWOyoV9tk7boQMPu8Iw==$tKuZniNJrMWGpwsjSJQrN7wSaeHWIxO+c8lXgvB5hzY=",
                            Uloga = 0
                        });
                });

            modelBuilder.Entity("SredstvaData.Models.Popis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumPopisa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Godina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KomisijaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KomisijaId");

                    b.ToTable("Popisi");
                });

            modelBuilder.Entity("SredstvaData.Models.PopisnaStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("KnjiznaKolicina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KnjiznaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PopisId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PopisanaKolicina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProcenjenaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SredstvoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PopisId");

                    b.HasIndex("SredstvoId");

                    b.ToTable("PopisneStavke");
                });

            modelBuilder.Entity("SredstvaData.Models.Prijava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmortizacionaGrupa1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmortizacionaGrupa2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrNal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojFakture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BrojNalaznice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumAktiviranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DatumFakture")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GodNal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventarskiBroj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JedinicaMere")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Knjizen")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObracunskaJedinica")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OtpisanaVrednost")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedBroj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevalorizacionaGrupa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SredstvoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("StopaAmortizacije")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DobavljacId");

                    b.HasIndex("SredstvoId");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("SredstvaData.Models.Rashod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojNaloga")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("DokumentBroj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Knjizen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KodTekst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ObracunskaJedinica")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Podaci")
                        .HasColumnType("TEXT");

                    b.Property<int>("RedBroj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SredstvoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SredstvoId");

                    b.ToTable("Rashodi");
                });

            modelBuilder.Entity("SredstvaData.Models.Sredstvo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmortizacionaGrupa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumAktiviranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumNabavke")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventarskiBroj")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("IspravkaVrednosti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("JeAktivno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Kolicina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Konto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("LegacySifra")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NabavnaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ObracunskaJedinica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PoreskaGrupa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PoreskaIspravkaVrednosti")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PoreskaNabavnaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PoreskaStopa")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RezidualnaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SadasnjaVrednost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StopaAmortizacije")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Sredstva");
                });

            modelBuilder.Entity("SredstvaData.Models.ClanKomisije", b =>
                {
                    b.HasOne("SredstvaData.Models.Komisija", "Komisija")
                        .WithMany("Clanovi")
                        .HasForeignKey("KomisijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Komisija");
                });

            modelBuilder.Entity("SredstvaData.Models.Kartica", b =>
                {
                    b.HasOne("SredstvaData.Models.Sredstvo", "Sredstvo")
                        .WithMany("Kartice")
                        .HasForeignKey("SredstvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sredstvo");
                });

            modelBuilder.Entity("SredstvaData.Models.Popis", b =>
                {
                    b.HasOne("SredstvaData.Models.Komisija", "Komisija")
                        .WithMany("Popisi")
                        .HasForeignKey("KomisijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Komisija");
                });

            modelBuilder.Entity("SredstvaData.Models.PopisnaStavka", b =>
                {
                    b.HasOne("SredstvaData.Models.Popis", "Popis")
                        .WithMany("Stavke")
                        .HasForeignKey("PopisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SredstvaData.Models.Sredstvo", "Sredstvo")
                        .WithMany()
                        .HasForeignKey("SredstvoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Popis");

                    b.Navigation("Sredstvo");
                });

            modelBuilder.Entity("SredstvaData.Models.Prijava", b =>
                {
                    b.HasOne("SredstvaData.Models.Dobavljac", "Dobavljac")
                        .WithMany("Prijave")
                        .HasForeignKey("DobavljacId");

                    b.HasOne("SredstvaData.Models.Sredstvo", "Sredstvo")
                        .WithMany("Prijave")
                        .HasForeignKey("SredstvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dobavljac");

                    b.Navigation("Sredstvo");
                });

            modelBuilder.Entity("SredstvaData.Models.Rashod", b =>
                {
                    b.HasOne("SredstvaData.Models.Sredstvo", "Sredstvo")
                        .WithMany("Rashodi")
                        .HasForeignKey("SredstvoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sredstvo");
                });

            modelBuilder.Entity("SredstvaData.Models.Dobavljac", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("SredstvaData.Models.Komisija", b =>
                {
                    b.Navigation("Clanovi");

                    b.Navigation("Popisi");
                });

            modelBuilder.Entity("SredstvaData.Models.Popis", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("SredstvaData.Models.Sredstvo", b =>
                {
                    b.Navigation("Kartice");

                    b.Navigation("Prijave");

                    b.Navigation("Rashodi");
                });
#pragma warning restore 612, 618
        }
    }
}
